name: Hugo-CI
on:
  push:
    branches: [ master ]
    paths:
      - 'Docs/**'

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: build Hugo public site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.SSHPORT }}
        script: |
          cd aspose-html-docs
          git clone --single-branch --branch master https://github.com/aspose-html/Aspose.HTML-for-Java.git || (cd Aspose.HTML-for-Java; git pull)
          cp -R Aspose.HTML-for-Java/Docs/* aspose-prototype-html/content/java
          cd aspose-prototype-html
          hugo --baseURL https://docs.aspose.com/html
          sudo cp -R public/java/* ${{ secrets.PROJECTPATH }}
          sudo nginx -s reload