name: Hugo-CI
on:
  push:
    branches: [ develop ]
    paths:
      - 'Docs/**'

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-github]
    steps:
      - name: hugo build
        run: |
          cd aspose-html-docs
          git clone --single-branch --branch develop https://github.com/aspose-html/Aspose.HTML-for-Java.git || (cd Aspose.HTML-for-Java; git pull)
          git clone --single-branch --branch master https://git.dev.dynabic.com/containerize-hugo/lutsk-aspose-prototype.git || (cd lutsk-aspose-prototype; git pull)
          cd lutsk-aspose-prototype
          git clone --single-branch --branch master https://git.dev.dynabic.com/containerize-hugo/lutsk-aspose-theme.git || (cd lutsk-aspose-theme; git pull)
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
          cp -R ${{ secrets.PROJECTPATH }}/Aspose.HTML-for-Java/Docs/* content/java
          hugo --baseURL https://docs.aspose.com/html
          scp -r public/java/* ${{ secrets.TRANSFERPATH }}
      - name: hugo deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            sudo cp -R ${{ secrets.PUBLICCONTENTPATH }} ${{ secrets.DEPLOYPATH }}
            sudo nginx -s reload